config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  post '/post_id/comments', to: 'comments#new' 
  devise_for :users
  resources :posts do 
    resources :likes
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :comments 
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	#before_action :configure_permitted_parameters, if: :devise_controller?
	protect_from_forgery with: :null_session
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   
    def new
        @comment = Comment.new
    end
    
   def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to root_path
  end

   
    def show
        @comment = Comment.find([:post_id])
        @comment = post.comment.all
    end


    private

    def comment_params
        params.require(:comment).permit(:id, :post_id, :user_id, :content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :find_post
	before_action :find_like, only: [:destroy]

	def create
		@post.likes.create(user_id: current_user.id)
    	redirect_to post_path(@post)
  	end

	def destroy
		if !(already_liked?)
			flash[:notice] = "Can't Unlike"
		else
			@like.destroy
		end
			redirect_to post_path(@post)
	end

	private

	def find_post
		@post = Post.find(params[:post_id])
	end

	def already_liked?
  		Like.where(user_id: current_user.id, post_id:
  		params[:post_id]).exists?
	end

	def find_like
   		@like = @post.likes.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @comments = Comment.all
  end

  def new
    @post = Post.new
    @like = Like.all
  end

  # def create
  #   @post = Post.new(post_params)
  #   @post.save
  #   @posts = Post.all
  # end

 def create
    @post = Post.new(post_params)
    @posts = Post.all
    if @post.save
      redirect_to @post
    else
      render "new"
    end
  end
    
  
  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    if @post.destroy
      redirect_to root_path, notice: "Post deleted."
    end
  end

  private
  def post_params
    params.require(:post).permit(:id, :user_id, :title, :text)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
	
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = User.posts.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
        redirect_to root_path, notice: "User deleted."
    end
  end


  private
  def user_params
    params.require(:user).permit(:email, :user_id, :username, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/comments/_form.html.erb
<fieldset>
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
	<%= form.hidden_field :user_id, value: current_user.id %>
	<%= form.label :comment %>
	<%= form.text_area :content %>
	<%= form.submit %>
<%end%>
</fieldset>

app/views/comments/new.html.erb
<p><%= render  "comments/form", comment: @comment %></p>

app/views/comments/show.html.erb
<table>
 	<tr>
 		<th>Comments:</th>
 		<td><% @comments.each do |comment| %></td>
 		<%# if current_user.id == post.user_id %><br>
 		<td><%= comment.content %></td>
 		<%end%>
 	</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postlikecomment</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
 <%= yield %>
</body>
</html>

app/views/posts/_dummy.html.erb
<%= link_to "Home", root_path %>
<center><%= link_to "New Post", new_post_path %></center>

<fieldset>
<table>
	<tr>
		<th>Title:</th>
		<th>Text:</th>
	</tr>
</table>
<br>

<% @posts.each do |post| %>
	<% if current_user.id == post.user_id %><br>
	<tr><%= post.title %></tr>
	<tr><%= post.text %></tr>

	<%= link_to 'Update', edit_post_path(post) %>
	<%= link_to 'Delete', post, method: :delete, data:{ confirm: "You sure?" } %>
	<%end%>
<%end%>

<%= render 'comments/form' %>

<% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
	<% if pre_like %>
   <%= button_to 'Unlike', post_like_path(post, pre_like), method: :delete %>
 <% else %>
  <%= button_to 'Like', post_likes_path(post), method: :post %>
 <% end %>
  	<p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

  	<%#= render "show", post: @post%>

<%= link_to "Back", :back%>
<%= link_to "Way Home", root_path %>

app/views/posts/_form.html.erb
<fieldset>
    <%= form_for(@post)  do |form| %>    
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title, placeholder: "Post Title" %>
    </div>
    <div>
        <%= form.label :text %><br>
        <%= form.text_area :text, placeholder: "Text" %>
    </div>
    <div>
        <%= form.hidden_field :user_id, value: current_user.id %>
    </div>
    <div>
        <%= form.submit %>
    </div>
    <%end%>
</fieldset>

app/views/posts/create.js.erb
$("#post").html("<%= j render partial: 'index', posts: @posts %>");
$("#new_post")[0].reset();

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<%= link_to "Home", root_path %>
<center><%= link_to "New Post", new_post_path %></center>

<fieldset>
<table>
	<tr>
		<th>Title:</th>
		<th>Text:</th>
	</tr>
</table>
<br>
<% @posts.each do |post| %>
	<% if current_user.id == post.user_id %>
	<tr><%= post.title %></tr>
	<tr><%= post.text %></tr>
	<br>

	<%= link_to 'Update', edit_post_path(post) %>
	<%= link_to 'Delete', post, method: :delete, data:{ confirm: "You sure?" } %>
	<br>
  <%end%>
<%end%>
<%#end%>

	<table>
 	<tr>
 		<th><b>Comments:</th><br
 		<td><% @comments.each do |comment| %></td>
 		<%# if current_user.id == post.user_id %>
 		<td><%= comment.content %></td>
 		<br>
 		<%#end%>
 		<%end%>
 	</tr>
</table>
</fieldset>



	

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1>Hello show</h1>
<table>
	<tr>
		<th>Title:</th>
		<th>Text:</th>
	</tr>

	<tr>
		<td><%= @post.title%></td>
		<td><%= @post.text%></td>
	</tr>
</table>


<%= render 'comments/form' %>
<%#debugger%>
<%#= render  "comments/form", comment: @comment %>
<%#= link_to "show comments", post_comments_path(@post)%>


<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
	<% if pre_like %>
   <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
 <% else %>
  <%= button_to 'Like', post_likes_path(@post), method: :post %>
 <% end %>
  	<p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

  	<%#= render "show", post: @post%>

<%= link_to "Back", :back%>
<%= link_to "Way Home", root_path %>

app/views/welcomes/index.html.erb
<h1>Hello</h1>
<center><h3>Postlikes</h3></center>
<fieldset>
	<center>
	  <% if user_signed_in? %>
	  <% current_user.email%>
	  <%= link_to "Show Post", posts_path %>		
		{<%= link_to 'Posts', posts_path %>}
		{<%= link_to "Edit", edit_user_registration_path %>}
		{<%= link_to "Logout", destroy_user_session_path, method: :delete %>}
	  <%else%>
		<%= link_to "Sign In",new_user_session_path %>
		||
		<%= link_to "New User", new_user_registration_path %>
	  <%end%>
	</center>
</fieldset>

app/views/welcomes/show.html.erb
<h1>Hello show</h1>
<table>
	<tr>
		<th>Title:</th>
		<th>Text:</th>
	</tr>

	<tr>
		<td><%= @post.title %></td>
		<td><%= @post.text %></td>
	</tr>
</table>

<table>
	<tr>
		<th>Comments:</th>
	</tr>
	<tr>
		<td><%= @comment.content %></td>
	</tr>
</table>

<%#= link_to "Home", root_path %>